[package]
name = "repro"
version = "0.1.0"
authors = ["Matt Miller <mmiller@hick.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
